{% set name = "pysparkling" %}
{% set version = "0.6.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pysparkling-{{ version }}.tar.gz
  sha256: 74056d975fa06bb9c4a73c91e8f7e7115089249a8cdeb7692f9a7c7ec0dc0a44

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - boto >=2.36.0
    - future >=0.15
    - python >=3.6
    - python-dateutil >=2.8.0
    - pytz >=2019.3
    - requests >=2.6.0

test:
  imports:
    - pysparkling
    - pysparkling.fileio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/svenkreiss/pysparkling
  summary: Pure Python implementation of the Spark RDD interface.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cdesouza21
